### ISSUE TITLE
Implement API function GetStreamTimes

### ISSUE THREAD

**Issue by cspack77** [janbar/pvr.mythtv#101]
Due to recent Kodi PVR changes in master branch, time shifting commands (Pause, StepBack, StepForward, etc.) are currently non-functional with Live TV. Per @ksooo, to restore this functionality "mythtv add-on must implement the PVR add-on API function GetStreamTimes".

**Comment by janbar** [comment]
It had to be implemented only for addon that handles demux. Since Krypton releasing the addon no longer handles demux.
I will try it, even I use it every day i didn't see an issue.

**Comment by janbar** [comment]
The function returns a type that includes pts codes. It can't be handle by addon since doesn't handle demux.
So is there an other issue somewhere since recent changes ? @ksooo

**Comment by ksooo** [comment]
If the addon no longer implements timeshifting, this function needs not to be implemented.

If the addon no longer implements timeshifting it is correct, that Kodi does no longer provide timeshifting functionality (for example, the OSD pause button and seek controls will be missing). Kodi does not offer any generic timeshifting functionality. This must come from the addon.

If the addon implements timeshifting (implements own client-side timeshifting buffer or provides access to a server-side timeshifting buffer), then GetStreamTimes must be implemented.

**Comment by cspack77** [comment]
@ksooo Yes it was functional with earlier Leia alpha builds. It seems to have stopped working somewhere between Aug 15 (09bff6a) and Aug 22 (1cbdec1). I can try and narrow it down further if needed.

**Comment by janbar** [comment]
@ksooo the addon implements timeshifting. But the new function to implement requires some data that  cannot be retrieved if you don't handle demuxing. That is the PTS. The pts can  be retrieved if you demux the stream packets, else no way.
So is timeshifting is only available now for addon handles demuxing ?

**Comment by janbar** [comment]
@FernetMenta, is there a workaround to enable the timeshifting feature for addon doesn't handle demuxing ?
Because without demuxing == no pts

**Comment by FernetMenta** [comment]
Demuxer is no requirement for ts. Check dvbviewer

**Comment by janbar** [comment]
@FernetMenta , thanks. I just reread coments about the initial PR. It should be resolved soon.

**Comment by janbar** [comment]
@cspack77 , I fixed the issue with the new version 5.8.5 of the addon.

**Comment by cspack77** [comment]
Confirmed timeshifting is working again with 5.8.5. Thank you @janbar and @ksooo.
