### ISSUE TITLE
Bug: Wrong recording length on playback, affects seeking.

### ISSUE THREAD

**Issue by Miwer** [janbar/pvr.mythtv#106]
Hi,

I just want to report a bug I found in 5.8.10 - I think it's somehow related to issue #30, which was recently fixed.

Some of my recordings shows a length during playback that is shorter than it actually is (the pos/length time shown during playback). Common for these recordings is, that I started watching them, while the recording was in progress. While the fix in #30 makes the end time update, as the recording is progressing, when the recording is done, it seems to have 'stamped' (for a lack of better word) the length as it was at the time I started watching the recording.

Example:
* Schedule recording at 20:00 
* Start watching recording at 20:12, while the recording is in progress
* When recording is done, and I want to rewatch the recording, it now shows a length of 12 minutes, even though the recording might be an hour long.
Also I cannot step skip beyond the 'false' recording length. Fast forward works.

**Comment by Miwer** [comment]
Just want to clarify, that I don't believe the fix mentioned in #30 is the cause of this issue, as my wording might seem to suggest.

**Comment by janbar** [comment]
I am trying to reproduce the bug here, doing as you explained.

**Comment by janbar** [comment]
I haven't the issue here. Re-watching the recording the length is right. If I remember there is a thread of the forum where a guy explained a similar issue. But I never reproduce it.
Also the addon transfers to kodi the recording start time and the total duration of the recording schedule. So the root cause can't be in the addon itself, but probably caused by some calculation in kodi.
You should open a ticket to kodi track to resolve the bug. This bug could also affect only your platform. Here I tested on Linux64 and OSX64.

**Comment by Miwer** [comment]
Hmm... this is funky - I cannot reproduce it either now, and I cannot find any corroborative evidence in the debug log either... quite the opposite actually. On playback I can see some LengthRecordedStream from the pvr client, and ffmpeg reports the correct length.

Recording 1 (reproduce attempt) -  22 minutes - reports correct, and skipping works

    01:13:48.036 T:3929727856   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream
    01:13:48.036 T:3929727856   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream: Done - duration: 1992689644
    ...
    01:13:48.122 T:3929727856    INFO: ffmpeg[EA3AE370]: Input #0, mpegts, from '(filename omitted)':
    01:13:48.122 T:3929727856    INFO: ffmpeg[EA3AE370]:   Duration: 00:22:03.38, start: 78988.627011, bitrate: 12046 kb/s

![recording1](https://user-images.githubusercontent.com/145515/47973077-765e1080-e0a2-11e8-9e8f-028269a00c9b.png)


Recording 2 (started watching during recording) - 85 minutes - reports 13:25, cannot skip beyond this point

    01:36:40.742 T:4021281648   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream
    01:36:40.742 T:4021281648   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream: Done - duration: 5552289916
    ...
    01:36:40.804 T:4021281648    INFO: ffmpeg[EFAFE370]: Input #0, mpegts, from '(filename omitted)':
    01:36:40.804 T:4021281648    INFO: ffmpeg[EFAFE370]:   Duration: 01:24:58.15, start: 86768.980933, bitrate: 8712 kb/s

![recording2](https://user-images.githubusercontent.com/145515/47973078-765e1080-e0a2-11e8-9043-d941b2dc4ecf.png)


Recording 3 (started watching during recording) - 145 minutter - reports 01:51, cannot skip beyond this point

    01:43:54.480 T:3510657904   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream
    01:43:54.480 T:3510657904   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream: Done - duration: 12720078496
    ...
    01:43:54.489 T:3510657904    INFO: ffmpeg[D1406370]: Input #0, mpegts, from '(filename omitted)':
    01:43:54.489 T:3510657904    INFO: ffmpeg[D1406370]:   Duration: 02:25:01.97, start: 65547.831178, bitrate: 11693 kb/s

![recording3](https://user-images.githubusercontent.com/145515/47973079-765e1080-e0a2-11e8-82b6-338354bc693f.png)


Recording 4 (don't remember) - 50 minutter - reports nothing, skip and ffwd/rew is not possible

    01:48:09.443 T:3948929904   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream
    01:48:09.443 T:3948929904   DEBUG: AddOnLog: MythTV PVR Client: LengthRecordedStream: Done - duration: 4469369308
    ...
    01:48:09.448 T:3948929904    INFO: ffmpeg[EB5FE370]: Input #0, mpegts, from '(filename omitted)':
    01:48:09.448 T:3948929904    INFO: ffmpeg[EB5FE370]:   Duration: 00:49:59.02, start: 14436.543800, bitrate: 11922 kb/s

![recording4](https://user-images.githubusercontent.com/145515/47973080-76f6a700-e0a2-11e8-99b2-faef6b1e947f.png)

Anyway, if you're certain that this is not a problem with the addon, then please go ahead and close this. It certainly looks this way from the logs. 

I must say that it puzzles me, how the Kodi player can get this wrong.

**Comment by janbar** [comment]
I found the bug and it affects only 32 bits platform as armv7. I fixed it in release 5.8.14.

**Comment by janbar** [comment]
You can test the fix installing the package for your platform:

https://jenkins.kodi.tv/blue/organizations/jenkins/janbar%2Fpvr.mythtv/detail/5.8.14-Leia/1/artifacts

**Comment by Miwer** [comment]
That's awesome - Thanks janbar.
However I don't think I can test with your builds, since CoreELEC is Linux, not android. I will either have to build CoreELEC and the plugin myself, or wait until they release the updated version in their repo. I'll get back to you on the test.

**Comment by Miwer** [comment]
I have tested 5.8.14 now, and all my recordings are showing correct length now. Thanks janbar.
