### ISSUE TITLE
Feature Request: Add option to set Default Recording Group as root for recordings

### ISSUE THREAD

**Issue by stsharp** [janbar/pvr.mythtv#110]
For users that only use one Recording Group (ie "Default"), can we create an option in the Add-On to set the Default Group as the root when browsing recordings?  Currently when going to recordings, there is one folder, "Default", and then we have to go through another click to view the list of recordings.  If the option is selected when you hit recordings, you would directly view everything in the Default recording group without the extra step of selecting Default.

**Comment by janbar** [comment]
The feature has been added in version 5.10.2.
To enable the feature you have to check the option "Show default recording group as root" in preferences settings of the addon.
