### ISSUE TITLE
Recording: Only 1 of 2 audio channels available on playback (MythTV 30)

### ISSUE THREAD

**Issue by m-reiter** [janbar/pvr.mythtv#121]
I sought assistance for this on the forum but didn't get many replies there, so I'm trying again here:

I have recently recorded a programme that offers 2 audio tracks: Original audio and a commented track for the visually impaired. I can confirm that both tracks are actually present in the recording as I can select between them when playing the ASX stream from Mythweb through VLC.

However, playing the recording back in Kodi, only one stream is available. Selecting "change audio track" only presents one selection "ger" which, unfortunately, is the commented track.

This is MythTV 30.0 running on Ubuntu 18.04. I've experienced the issue in Kodi 18 both on Android (Fire TV stick) and on a Mac.

**Comment by janbar** [comment]
The addon doesn't handle the demux, so the issue seems to be related to the Kodi player.

**Comment by m-reiter** [comment]
Thankyou for the quick response! ~~Do you have any suggestion where I should take this issue or how I could go about debugging it further?~~

I've opened a Kodi issue: xbmc/xbmc#16211
