### ISSUE TITLE
Some recordings not showing up (Kodi 18 on FireTV Stick 4K)

### ISSUE THREAD

**Issue by m-reiter** [janbar/pvr.mythtv#122]
I currently have the issue that some recent MythTV recordings don't show up in Kodi 18 running on a FireTV stick 4K. The same recordings do show up in another instance of Kodi 18 running on a Mac (OS X 10.11).

The backend is version 2:30.0+fixes.201905010255.a32ec4b~ubuntu18.04.1 running on Ubuntu.

I don't see any systematics in which new recordings will show up and which won't apart from the fact that so far, new episodes of shows for which recordings already exist have always showed up.

Please let me know which additional details you need.

**Comment by m-reiter** [comment]
Sorry, this (non-)issue was a mistake on my side: The recordings *do* show up, but due to Kodi sorting "folders" (like series with multiple episodes) before "files" (like single recordings) they do so towards the bottom of the list after year-old series recordings. I simply hadn't expected that and didn't scroll down far enough.

Apologies if anybody already put any thought into this.

**Comment by janbar** [comment]
No problem. Have a good fun with kodi and mythtv
