### ISSUE TITLE
Protocol version needs updating

### ISSUE THREAD

**Issue by doc-jay** [janbar/pvr.mythtv#13]
Kodi version 15.1
Mythtv version:  mythbackend version: master [v0.28-pre-3051-gd03d51d] 

this is in my mythbackend.log:

Aug 21 18:45:46 mythtv mythbackend: mythbackend[6011]: C ProcessRequest mainserver.cpp:1549 (HandleVersion) MainServer: MainServer::HandleVersion - Client speaks protocol version 86 but we speak 87!

this is in my kodi.log

18:39:30 T:9152   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)Myth::ProtoBase::OpenConnection: failed to connect with any version

**Comment by janbar** [comment]
Thanks. I will update soon.

**Comment by janbar** [comment]
fixed in version:
- 2.6.1 for Isengard
- 1.13.1 for Helix
- 1.9.22-61 for Gotham
