### ISSUE TITLE
Commercial Cut lists not skipping

### ISSUE THREAD

**Issue by Zandengoff** [janbar/pvr.mythtv#136]
Have multiple Kodi instances running PVR client 5.10.13. I had the settings set to dialog for cut lists and noticed recently that I was not being prompted and no commercials were being skipped. Upon changing the setting to always for cut lists, I noticed that no commercials are being skipped for any recording, new or old. I tested with recordings that had commercial cut lists that auto skipped in the past and they seem to also be affected. I have manually run the commercial detection on new recordings on the backend and they indicate a cutlist has been generated. Backend is MythTV 29.

**Comment by janbar** [comment]
have you enabled the transcoding of recordings ?

**Comment by Zandengoff** [comment]
I have not enabled transcoding. The files in question are mpeg2 ts files. All files have been run through commercial detection and show commercials as flagged in the MythTV metadata.

**Comment by Zandengoff** [comment]
I just got the update to Kodi for 18.5 compiled on 12-5-2019 which updated the mythtv pvr to 5.10.14 and the issue seems to be resolved. So don't know if it was Kodi or the plug-in that did it, but all is working again.

**Comment by willat8** [comment]
I confirm I had the same problem as OP and that Kodi 18.5 fixed it for me too.

**Comment by janbar** [comment]
That's welcome. Nothing changed in the addon for this issue, so Kodi 18.5 fixed it.
