### ISSUE TITLE
Support for MythTV v31

### ISSUE THREAD

**Issue by yasij** [janbar/pvr.mythtv#145]
MythTV 31 was release on Mar 23, 2020. API changes are listed [here](https://www.mythtv.org/wiki/API_parameters_31).
 
There are a few APIs listed as changed in that document:
Guide/GetProgramGuide
Guide/GetProgramList
Channel/AddDBChannel
Channel/AddVideoSource
Channel/GetChannelInfoList
Channel/UpdateDBChannel
Channel/UpdateVideoSource

There is also one new API:
Myth/DelayShutdown

Does kodi-pvr-mythtv already support the new APIs, or does it need an update?

**Comment by janbar** [comment]
It should. I have to check with the last released commits. I let you know soon.

**Comment by janbar** [comment]
I just finished to compile mythtv-31 and install it on my server and that work great !

![Capture du 2020-04-11 21-09-37](https://user-images.githubusercontent.com/2353635/79052753-ef1eb000-7c38-11ea-9909-5e82974ac959.png)

**Comment by janbar** [comment]
I will update the change log in the addon for Matrix. Also the addon for Lea works the same.

**Comment by yasij** [comment]
Thanks. After your comment, I upgraded using the mythbuntu 31 ppa. It's working great here,t oo. Thanks.
