### ISSUE TITLE
Coverart issues

### ISSUE THREAD

**Issue by mataus19** [janbar/pvr.mythtv#153]
Hi, I'm having issues with Kodi pulling the correct coverart from my server when using the stock Estuary skin (latest version of Kodi on CoreElec 9.2.3)

I've searched all the forums but can't seem to find a solution.

When highlighting recordings the correct fanart is shown however the coverart does not show. Instead it shows a landscape 'screenshot' of the recording. This is the image that is stored in the same directory as the recording. I've tried numerous other skins and I get the same problem.

I have an Intel NUC running Xubuntu with Mythtv backend and frontend (V31). I have 3 separate Kodi clients that access the backend.

I have correctly setup the directories for the Coverart, Fanart and Banners in the backend and they all have the correct permissions set. I've proven that all 3 directories can be read from. I setup a Raspberry Pi4 running Mythtv Lite and the Pi connects to the backend database and correctly pulls the correct Coverart and Fanart.

Any advice would be appreciated. Thanks!

**Comment by janbar** [comment]
Hi,
Currently the addon retrieves the coverart, fanart, and thumbnail of recordings from the backend. But the skin Estuary never display the cover: That the same thing here. The fanart is printed as background and the thumbnail is show in the information panel.
I will override the thumbnail with the cover to fix this behavior in the next commit.

**Comment by janbar** [comment]
I made the change in Leia and Matrix branches: 5.10.18 , 7.0.4

**Comment by mataus19** [comment]
Just updated the Kodi addon and it's working great. Thanks!
