### ISSUE TITLE
Kodi pvr api is now 4.1.0

### ISSUE THREAD

**Issue by barttp** [janbar/pvr.mythtv#16]
This is probably not a bug however. I compiled a new kodi build and noticed that I had a version mismatch trying to install the mythtv pvr addon. Did a little digging and found the following:

"addon.xml  [PVR] bump API version to 4.1.0 a day ago"

https://github.com/xbmc/xbmc/tree/master/addons/xbmc.pvr

Looking at my logs the mythtv.pvr addon is still expecting 4.0.0.

**Comment by janbar** [comment]
Hi, the new api 4.1.0 has been merged. Pull latest commit and rebuild the addon, it will generate the addon for the latest kodi.
