### ISSUE TITLE
Rewind liveTV doesn't work with Matrix

### ISSUE THREAD

**Issue by yasij** [janbar/pvr.mythtv#162]
Kodi Matrix 19.0
kodi-pvr-mythtv 7.3.0
Kubuntu 20.10
MythTV 31

When playing LiveTV and pressing rewind, playback momentarily stops like it's rewinding but it resumes from live playback.

Another user has also reported this on the kodi [forums](https://forum.kodi.tv/showthread.php?tid=360616).

**Comment by willat8** [comment]
I confirm this same behaviour on Kodi for Android

**Comment by thadarkspark** [comment]
Hi,
I can confirm the exact same issue when I updated from Kodi 18.9 to 19.0 on my Bravia Android TV (with the Mythtv Addon)

I don't have the issue with the other 3x Kodi PC's running 18.9 on Xubuntu 20.04 (which don't auto update like Android TV), and it's also working correctly on a Xubuntu 20.04 VM.

I am running MythTV .31+fixes backend.

**Comment by janbar** [comment]
Hi, some changes haven't been implemented. I am working on it ...

**Comment by janbar** [comment]
Fixed with the release 7.3.1 (Matrix)
