### ISSUE TITLE
Translations at Weblate

### ISSUE THREAD

**Issue by gade01** [janbar/pvr.mythtv#166]
Hi @janbar 

Are you interested in having pvr.mythtv added for translations at Weblate?

If you are, please provide the following info:
- Branch to use
- Would you like PR's or direct pushes from Weblate? (PR's are safest, direct pushes are easiest)
- How often would you like PR's/direct pushes? Default is 5 days, but it's totally up to you.
- Do you want a version bump in addon.xml / news entry / changelog entry?

For your source en_gb file to get synced with Weblate, you need to add this webhook to your repo for the push event:
`https://kodi.weblate.cloud/hooks/github`

If direct pushes are wanted, you need to add Github user https://github.com/weblate as collaborator.
This user will automatically accept any collaboration within 5 minutes.
If PR's are the preferred method, Weblate will push to the same PR until merged or closed.

Cheers

**Comment by gade01** [comment]
@janbar 
I created the component at Weblate to get started with translations: https://kodi.weblate.cloud/projects/kodi-add-ons-pvr-clients/pvr-mythtv/

Do you prefer using master og Matrix branch?

**Comment by janbar** [comment]
IMO the "master" branch would be better. Thanks

**Comment by gade01** [comment]
Sounds perfect, thanks.

Please add the webhook for the push event as described above.
![webhook](https://inlinestudio.dk/xtra/kodi/weblate/webhook.png)

I'll PR a workflow to sync metadata from addon.xml to the language files and back.

**Comment by janbar** [comment]
Done

**Comment by gade01** [comment]
Great, thanks.
Everything is working now.
