### ISSUE TITLE
mythtv.gui version has been increased to 5.10.0

### ISSUE THREAD

**Issue by barttp** [janbar/pvr.mythtv#18]
Love testing this new stuff. :) 

```
<import addon="xbmc.gui" version="5.8.0"/>
```

Looks like the version is 5.10.0 and we are trying to import 5.8.0

https://github.com/xbmc/xbmc/blob/master/addons/xbmc.gui/addon.xml

<addon id="xbmc.gui" version="5.10.0" provider-name="Team-Kodi">
  <backwards-compatibility abi="5.9.0"/>

**Comment by janbar** [comment]
Updated. Thanks.
