### ISSUE TITLE
Audio sync problem with playing recordings

### ISSUE THREAD

**Issue by bennettpeter** [janbar/pvr.mythtv#20]
I am using Kodi Isengard version with pvr.mythtv Isengard source version from the download page, on Raspberry Pi 2

When playing a recording, if I use the forward and back arrows to skip commercials, the audio becomes unsynchronized. Lip-sync is incorrect. Stopping play and resuming fixes it, also switching from analog to digital audio and back to analog fixes it. Pausing does not help, when resuming it is still unsynchronized.

This problem also existed with the Helix version. It has got worse with isengard. With Helix it happened occasionally, but with Isengard it happens almost every time I skip.

**Comment by nxdefiant** [comment]
Same problem on raspbian jessie with kodi from http://michael.gorven.za.net/raspberrypi/xbmc

Were you able to fix this?

**Comment by janbar** [comment]
Nothing can be fixed in addon, the original issue is in xbmc itself, probably in omxplayer.

**Comment by bennettpeter** [comment]
This is a problem with the TS MPG files that mythtv creates. A workaround I used is to convert the files in mythtv to mkv files with a user job. I convert to mkv using program mkvmerge, without transcoding. Conversion is very quick.

**Comment by janbar** [comment]
Could you open a track ticket for kodi ?

**Comment by nxdefiant** [comment]
Done: http://trac.kodi.tv/ticket/16611

**Comment by janbar** [comment]
@nxdefiant , thanks

**Comment by nxdefiant** [comment]
hmm, can someone with an rpi test this issue with an order kernel, e.g. 3.18?

```
rpi-update 33a6707cf1c96b8a2b5dac2ac9dead590db9fcaa
```

**Comment by bennettpeter** [comment]
Closing this because it is very old.
