### ISSUE TITLE
Recording Metadata availability in Kodi

### ISSUE THREAD

**Issue by ineffablebob** [janbar/pvr.mythtv#21]
I know that Myth will find metadata for recordings (typically via a job run directly after the recording completes). This is data like the TVDB ID, show name, season, episode name/number, air date, etc of the recording. I'd like to make use of this information in Kodi, but as far as I can tell, the PVR addon isn't setting it anywhere. The only information I can find is the "label" which looks like "Show Name - Episode Name".

Once a video starts playing, I'm using the Player.GetItem method that Kodi provides (http://kodi.wiki/view/JSON-RPC_API/v6#Player.GetItem). This is returning data like this:

{u'item': {u'type': u'unknown', u'id': 4, u'label': u'The Flash - The Darkness and the Light'}}

There's an ID and that label. The ID doesn't seem to correspond to the Kodi media library, so I'm not sure what it's referring to. (I tried VideoLibrary.GetMovieDetails, VideoLibrary.GetEpisodeDetails, and VideoLibrary.GetTVShowDetails using the ID, but they all returned nothing.) The label appears to be the same value that I see in the recordings list.

Would it be possible to add the additional metadata that Myth knows to the video playback metadata? One possible method would be to set the video player InfoLabel values (http://kodi.wiki/view/InfoLabels#Video_player) like TVShowTitle, Episode, etc. Or fill in more values in the data structure returned by that Player.GetItem call.

**Comment by janbar** [comment]
Lot of recording details are transferred to kodi core as you can see here: https://github.com/janbar/pvr.mythtv/blob/doityourself/lib/kodi/pvr/xbmc_pvr_types.h#L436 .
So seems json rpc doesn't bind them or badly. We have to look in kodi code to known why.
