### ISSUE TITLE
No "Omega" support

### ISSUE THREAD

**Issue by ksooo** [janbar/pvr.mythtv#211]
There is no Omega branch available in this repo, thus no builds for Omega available, and we are nearing Omega release. 
@janbar what is your plan regarding Omega support for this add-on?

**Comment by janbar** [comment]
No branch Omega in the Kodi repo yet. So the build will use master as ref.

See commit 1f743a65a9e04159a083325b2cec4a6ae4848c13

**Comment by janbar** [comment]
New branch Omega has been initialized. Thanks for the remainder.

**Comment by ksooo** [comment]
> No branch Omega in the Kodi repo yet. So the build will use master as ref.

 That is not the criteria. xbmc and add-ons (all binary add-ons, not only pvr add-ons) use a different branching model.
 
 xbmc creates an Omega branch very late in the release cycle, usually when xbmc enters RC phase.
 In difference, the bin add-ons need to be branched very early in the release cycle, namely as soon as xbmc branches for the current version to be released.
 
 I know this is confusing and not invented by me, but it is like this. if you don't follow this, you will not be able to relase any Omega add-ons until you branch. But usually you want to be able to deliver pre-release add-on version even for Omega alphas and betas, right?
 
 Example:
 
 Nexus going into RC phase => Nexus branch created in xbmc repo master from that moment on for next Kodi version, Omega. All add-on repos need to create an Omega branch asap.

So dev for Omega will be done on xbmc master, but on Omega branch for the add-ons.

**Comment by ksooo** [comment]
So, you should have had an Omega branch for a long time already. Not having it results in non pvr.mythtv add-on being available in the Omega add.on repo as of now. If that is what you want, to enter the Omega dev cycle very late, so be it. Just saying that you do it different from every other bin add-on.

master branch is basically dead and pointless for bin add-ons.

And please, I do not want to discuss whether this is bad or good, just pointing out the consequences of what your are currently doing.

Lastly, this has bin so for a long time, nothing invented for Omega.

**Comment by janbar** [comment]
Yep, I know that.

> So the build will use master as ref.

I means the workflow build uses the master branch of kodi. Therefore I will have to change that later, once the Kodi will have Omega branch.

**Comment by ksooo** [comment]
As I see it you just released 21.0.0 from the master branch of your repo. That's not resulting in a new add-on version in the Omega Kodi add-on repo! You need to release from your Omega branch.

> I means the workflow build uses the master branch of kodi. Therefore I will have to change that later, once the Kodi will have Omega branch.

 That's okay.

**Comment by ksooo** [comment]
@janbar can this issue be closed?

**Comment by janbar** [comment]
I closed it
