### ISSUE TITLE
make install going to the wrong place?

### ISSUE THREAD

**Issue by mdeguzis** [janbar/pvr.mythtv#22]
I'm trying to package this for SteamOS, and everything seems to go fine, and pre-tests of `make install` put things into two directory paths, as noted in the [install file](https://github.com/janbar/pvr.mythtv/blob/doityourself/debian/kodi-pvr-mythtv-dev.install). Is there some kind of reason why Kodi won't recognize this? As a test, I've also tried giving more (up to 777) permissions to the directory and sub directories.

```
desktop@steamos:~/pvr.mythtv/build$ ls -la /usr/local/share/kodi/addons/pvr.mythtv/total 1200
drwxr-xr-x 3 steam steam    4096 Nov 14 20:41 .
drwxr-sr-x 3 steam steam    4096 Nov 14 17:24 ..
-rw-r--r-- 1 steam steam   22152 Nov 14 20:39 addon.xml
-rw-r--r-- 1 steam steam    4695 Nov 14 20:39 changelog.txt
-rw-r--r-- 1 steam steam   54653 Nov 14 20:39 icon.png
-rw-r--r-- 1 steam steam 1122624 Nov 14 17:23 pvr.mythtv.so
drwxr-xr-x 3 steam steam    4096 Nov 14 20:41 resources
``
```

**Comment by janbar** [comment]
It depends of `INSTALL_PREFIX` or `CMAKE_INSTALL_PREFIX`, which drives where kodi is installed: `/usr` or `/usr/local`. And then "lib" files are installed in `$INSTALL_PREFIX/lib/kodi/` and "resource" files are installed in `$INSTALL_PREFIX/share/kodi/`.
Here https://launchpad.net/~jlbarriere68/+archive/ubuntu/ppa/+files/kodi-pvr-mythtv-dev_3%7E551%7Eubuntu14.04.1_i386.deb , you will find a sample of deb package made with my launchpad account. Generally `INSTALL_PREFIX` is set with `/usr` for public package.

**Comment by mdeguzis** [comment]
Ok, thank you for clearing this up, I plan on doing some packaging for SteamOS-Tools today, and i'll make sure I check all of this out. Thank you very much.

**Comment by mdeguzis** [comment]
@janbar , sorry I forgot to close this.
