### ISSUE TITLE
Please stop asking ImageFactory with application/octet-stream mimeType

### ISSUE THREAD

**Issue by fritsch** [janbar/pvr.mythtv#23]
Hi,

myth removes the file endings of its thumbnail / coverart cache files and later asks kodi's ImageFactory to produce a thumbnail while asking it with application/octet-stream mimetype.

It would be nice if you could fix that out of spec behaviour. I don't like to parse octet-streams for valid image data.

Thread: http://forum.kodi.tv/showthread.php?tid=250817&pid=2192159#pid2192159

**Comment by fritsch** [comment]
https://github.com/fritsch/xbmc/commit/e6e1a222cf5cfc18b192d041450b4b587a8ee7a0 <- should workaround this issue, but I'd really like to avoid it

**Comment by janbar** [comment]
Hi fritsh. Yes i can parse the required extension from the source name. I will check that and come back.

**Comment by fritsch** [comment]
For now I have workarounded those (as long as you only use png / jpg) where it is very easy to check the file header. Btw. you don't need the extensions - if you supply the correct mime_type it would also be fine.

**Comment by janbar** [comment]
Fritsch, the PVR api doesn't allow to transfer any mime type for icon path, even for channels or recordings. So what do you prefer ? No change or an extension ?

**Comment by fritsch** [comment]
Extension, please - makes it much easier for external programs. Think of image viewers.

**Comment by fritsch** [comment]
And thx much btw.!

**Comment by janbar** [comment]
Little more complex, I get the mime type after i assigned the cache filename for each item. Reason is file paths are transfered using pvr api, and all downloads of image are delayed to a worker thread, and only the worker can know the mime type.
Depending of backend version, i download images using proprietary protocol or http :(.  It is one of the reason i use a local cache. If i enable only http transfer then i pass directly the url of image in the path and let xbmc downloading them. But i am afraid xbmc uses massive threading to load them and then breaks others transfer from the backend like video stream.

**Comment by fritsch** [comment]
Not good at all. So you just generate a random file name and later on the worker writes the data? Blocking and waiting is certainly not an option, yes.

And the PVR Api removes the trailing extension already? If that would also be shipped - no issue, right?

**Comment by janbar** [comment]
Yes i generate filename using uid of owner (no extension), and later the worker writes the data.

The api accepts an URI: local file or proto://... , for instance i set the generated filename above.

I become to think your "workaround" is a golden fix.

**Comment by fritsch** [comment]
So why do you generate the filename without extension? Cause you just don't have the knowledge about the content?

**Comment by janbar** [comment]
Yes i don't

**Comment by janbar** [comment]
and checking the cache mime type varying for a same icon type (channel, fanart ...) between png ot jpeg

**Comment by janbar** [comment]
Only the worker thread know the mime type when it download stream. But it is too late ... the filename has already been provided to the api

**Comment by janbar** [comment]
Is exist a wrapper format for image ?

**Comment by fritsch** [comment]
Sorry - I did not get the last question. Can you point me to the code in your addon that handles those?

**Comment by janbar** [comment]
https://github.com/janbar/pvr.mythtv/blob/doityourself/src/fileOps.cpp#L267

**Comment by janbar** [comment]
and the filename is generated at https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L622 for channels

**Comment by janbar** [comment]
same for recordings: https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L907

**Comment by fritsch** [comment]
No idea what this here is: https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L628

And I also don't know how the jobs you have there are going into your queue - myth specific? Why not communicate the type within those - as the jobs are objects anyways?

**Comment by janbar** [comment]
Line 628: not related with icon. It is the type of channel stream for network channel.

The job is pushed in the queue when calling to generate the filename (line 622 or 907)

**Comment by janbar** [comment]
-> https://github.com/janbar/pvr.mythtv/blob/doityourself/src/fileOps.cpp#L65

**Comment by janbar** [comment]
The only way to know the mime type is to download the stream. So to fix it i would have to set directly the URI of icon instead provide a local filename. But i afraid many users complain because xbmc massively download images from their backend ;).

**Comment by janbar** [comment]
Here the job process() download one file at time. Also i suspend the job during playback.

**Comment by fritsch** [comment]
as said - I will workaround that in core now without massive overhead ... but throwing binary buffers to someone and say: guess what's in there - I tell you it's application/octet-stream is not nice ...

and don't know much about pvr / myth api and so on ... just saying: if would not be so easy for png / jpeg - I would have refused to fully parse those binary files with ffmpeg to find something it could understand as this will drive low performant clients into 100% CPU.

**Comment by janbar** [comment]
Only jpeg and png are provided by myth backend. So please merge your workaround. I will think later how i could refactor the stuff to provide the extension, but it seems to be hard at this late hour ;).

**Comment by janbar** [comment]
... and thanks for your time Fritsch

**Comment by fritsch** [comment]
The workaround won't be needed as of now - but I plan to remove cximage from kodi completely, will save us some 20 thousand lines of code ... it gets replaced with ffmpeg image loader, which was tested in that forum thread. So I gather use cases currently and try to fix them all.
