### ISSUE TITLE
EGP only shows three day's worth of program, mythfrontend shows 14.

### ISSUE THREAD

**Issue by DrTron** [janbar/pvr.mythtv#247]
All,
I'm using kodi built from source on Debian Stable, along with the prv.mythtv-addon (currently v21.1.9).
In mythtv-frontend, as well as when looking directly into the EPG database, I see EPG data 14 days out.
However, in Kodi, the mythtv-addon only shows three days.

I don't often look that far forward, but I remember it showing all 14 days in the past.

Thanks!

**Comment by janbar** [comment]
There is a setting in Kodi to configure the number of days to show.:See settings->PVR. By default only 3 days are shown.

**Comment by DrTron** [comment]
Ah, within the Kodi settings and not within the Mythtv-Addon-Settings?
Thanks, I'll have to check that...

**Comment by DrTron** [comment]
That was it, I totally looked in the wrong place. 
Thanks for the hint!
