### ISSUE TITLE
Improvement: Skip Storage Group selection if there's only one

### ISSUE THREAD

**Issue by citronalco** [janbar/pvr.mythtv#25]
When watching recordings: If there's only a single MythTV Storage Group please do not ask the user which storage group to use, just use it. This simple change would improve usability quite a lot :)

**Comment by janbar** [comment]
Hi @citronalco

You should have two recording groups at least: "Default" and "LiveTV"

**Comment by citronalco** [comment]
For some reason I only have "Default" as recording group. And sorry for mixing it up with storage groups.

**Comment by janbar** [comment]
Removong root folder (recording group) cannot be handled. Cause that merges all groups and users don't want this. You can manage your case by adding the folder 'Default' to kodi favorites, and then browse recordings from there.

**Comment by stsharp** [comment]
I wouldn't say that "all groups and users don't want this".  I would prefer not to have a Default folder - all of my recordings go to the Default Group, so there is an extra level to get to recordings.  Can we make this an option in the setup?  It could be something like "Use Default Group as Root".

**Comment by janbar** [comment]
I will see what I can do

**Comment by janbar** [comment]
This option "Use Default Group as Root" seems to be a good start. Also any others groups would be in sub-path.

**Comment by janbar** [comment]
superseded by #110

**Comment by janbar** [comment]
Resolved
