### ISSUE TITLE
Teletext unavailable.

### ISSUE THREAD

**Issue by kendokan** [janbar/pvr.mythtv#27]
I'm having a difficult time understanding if this is actually supposed to work or not. Teletext is available in the stream as verified by viewing closed captions using the Myth Frontend, but Kodi states Teletext is unavailable when selecting the option while watching a channel.

**Comment by janbar** [comment]
Yes , teletext is supposed to work. But i am no longer able to check it for 6 months in my country because no channel use it now. My last checking was using Kodi Isengard.
