### ISSUE TITLE
Disable autoexpire for recording

### ISSUE THREAD

**Issue by mindoms** [janbar/pvr.mythtv#31]
There is an option "Keep LiveTV recording" in the PVR client specific actions. But it would be nice to have a feature for disabling auto-expire for normal recordings. ( I say "disable autoexpire" instead of "keep recording" because these seem to be 2 separate things in mythtv context at least in the 'recorded' table, but probably the wording "keep recording" is better for use in kodi, idk)

I'm new to kodi plugins but as far as I can tell from the source this would be as simple as renaming the menu entry and removing two lines in PVRClientMythTV::CallMenuHook

```
if (!it->second.IsLiveTV())
  return PVR_ERROR_NO_ERROR;
```

because IsLiveTV() only checks if the recording is in the LiveTV recording group. And undeleteRecording() should be ignorant if it handles livetv or normal recordings as it only calls the webAPI.

Furthermore it would be great if recordings in the list or details page would reflect the recordings auto-expire status.

have a nice day and thanks for that great plugin.

**Comment by janbar** [comment]
Currently if the recording is not the current live then i call api command UndeleteRecording. After checking, you are right, the autoExpire flag is disabled by the api command. I will update sources to enable your request soon. Thanks.

**Comment by janbar** [comment]
About to reflect the autoexpire flag, it needs to update kodi pvr api and the kodi skins. Could you request the feature to kodi forum in the dedicated thread ?

**Comment by janbar** [comment]
For instance from addon side, i can only add a new menu hook to show the flag or add a tag in title. It could be do the work. I will check later if something exist i discarded.

**Comment by janbar** [comment]
Related changes have been merged.
