### ISSUE TITLE
remote mythtv backend not seen at startup

### ISSUE THREAD

**Issue by aklinbail** [janbar/pvr.mythtv#35]
Hi, 

I have a 24/7 always on Mythtv system on a home server (that also houses my media storage for the Kodi frontends. ) 

I have migrated the media frontend in the bedroom to openelec and am using the packaged version of the pvr.mythtv plugin. 

Whenever I startup the machine or resume from suspend, I get a message that the backend is not available" Mythtv PVR no response from backend. (although it is never shut down) 

I need to then go in a disable then re-enable the PVR system for the connection to be established. 

Other info
The system is connected via gigabit ethernet. 
I am using DHCP to assign a dynamic IP. 

Is there a setting that I need to modify or is this a potential bug

Regards

**Comment by aklinbail** [comment]
ok.. simply fixed by changing a setting in Kodi, to not start Kodi until networking was up..

**Comment by janbar** [comment]
What is the setting you have changed ?

**Comment by aklinbail** [comment]
Hi,
The setting is specific to OpenELEC.  In the OpenELEC settings menu under
Network,  selected "Wait for network before starting Kodi"
This fixes the problem for a shut down but not suspend..

**Comment by janbar** [comment]
Normally the addon receives signal from kodi before suspending to close connections with the backend. And then on wake-up it wait signal to reconnect to the backend. I did'nt check the feature since kodi 15. I will check it but sure behavior is updated in kodi for OpenELEC.

**Comment by aklinbail** [comment]
Is there anything you'd like me to test from my side?
