### ISSUE TITLE
Cannot compile for Kodi 17

### ISSUE THREAD

**Issue by fossum** [janbar/pvr.mythtv#36]
I know this is a little premature, but I just installed Kodi 17 on my Fedora box and I can't get MythTV to compile for it.

```
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;p8-platform
-- No platform specific file /home/gus/git/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
CMake Error at CMakeLists.txt:400 (message):
  pvr.mythtv: invalid or missing addon source directory at
  /home/gus/git/xbmc/project/pvr.mythtv


-- Configuring incomplete, errors occurred!
See also "/home/gus/git/pvr.mythtv/build/CMakeFiles/CMakeOutput.log".
[gus@localhost build]$ 
```

The CMakeOutput did not seem to have anything useful.

**Comment by fossum** [comment]
Sorry, I guess I was compiling from the original repo and not the Janbar one...

**Comment by janbar** [comment]
Seems there was changes in kodi cmake project breaking addons build.
Anyway, as you saw you can compile the pvr.mythtv addon for kodi 17 using the branch "doityourself" of my repo, which doesn't depend of kodi build system.

**Comment by fossum** [comment]
I think I was actually on master. What's the difference between the branches?
