### ISSUE TITLE
Problem connecting to latest release of MythTV .29

### ISSUE THREAD

**Issue by Neophraz** [janbar/pvr.mythtv#38]
Hi, I updated my MythTV backend yesterday and since the update, I have been receiving this message in Kodi:

![mythtv pvr error message](https://cloud.githubusercontent.com/assets/4356909/16062437/bac4d218-3258-11e6-9879-e1ea8d68d061.jpg)

I get this error message from my Linux Kodi as well as my Android Kodi. Any suggestions on what can be done to fix it? I haven't found any new release of the PVR addon that fixes it. Thanks for your help!

**Comment by Neophraz** [comment]
I spoke with a mythTV developer and he said they updated the protocol in the new .29 mythTV.
It's likely to be the protocol version that was updated from 88->89 on 11th June.
Any plans to update the PVR with the new version? My log file says:

15:51:50 T:140665874802432   ERROR: PVR - couldn't get the capabilities for add-on 'unknown'. Please contact the developer of this add-on: Christian Fetzer, Jean-Luc Barrière
15:51:50 T:140665874802432   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)OpenConnection: failed to connect with any version
15:51:50 T:140665874802432   ERROR: AddOnLog: MythTV PVR Client: Failed to connect to MythTV backend on 10.11.12.220:6543

I downloaded a copy of the src and can see:
<addon
  id="pvr.mythtv"
  version="4.5.1"
  name="MythTV PVR Client"

and I would update that version with a new version just to see what it does, except I'm not sure what the new version should be. If that's even the same thing....

**Comment by janbar** [comment]
The new version is supported with the latest commit ftom the development branch https://github.com/janbar/pvr.mythtv/commits/doityourself.
This branch is dedicated to kodi dev krypton only.

**Comment by janbar** [comment]
If you use kodi stable release (jarvis), then you should revert you mythtv backend upgrade. The stable release of mythtv is currently 0.28 and there is no plan to support v29 before kodi krypton is out.

**Comment by Neophraz** [comment]
Thanks for the info Janbar.
