### ISSUE TITLE
Padding time is defaulted to 30 minutes

### ISSUE THREAD

**Issue by voncloft** [janbar/pvr.mythtv#44]
When I go to the main screen for "TV" in the kodi program and click guide, I will right click the show I want to record - select "Record" and it seems okay - it starts at the designated time slot however my half hour shows become and hour, and my hour shows become an hour and a half.

However I noticed after I look at the timers section under the tv, after setting the recording it states the end padding time is 30 minutes, I have to manually change it to 0 otherwise the tv show will have extra "junk" in the file when played.

I checked the settings under kodi bin app for "live tv" under system settings and their default end pad is 0 minutes - I am assuming this is a bug in the addon.

**Comment by janbar** [comment]
Hi, have you checked setting of your backend ?
The addon doesn't use Kodi setting for padding time, but backend setting instead. Padding time could depend of your preferences by program genre etc...

**Comment by voncloft** [comment]
I use mythtvbackend and checked my recording profiles, I did not find anything stating a half hour for padding time.

**Comment by voncloft** [comment]
mythbackend

**Comment by voncloft** [comment]
wait I take that back, i ran mythtvfrontend and found out it was initially recording 30 minutes after the show, corrected to 0 got it working again - not sure where to look in mysql for it though :-/

safe to close ticket, thanks for your helping in the point of the right direction.
