### ISSUE TITLE
Only sync "visible" channels

### ISSUE THREAD

**Issue by 5im-0n** [janbar/pvr.mythtv#51]
There are a few hundred channels here, but only about 20 are really interesting, so I set the others to visible=false in mythtv.
It would be nice if there where an option to sync only visible channels from mythtv, so the program guide in kodi does not get messed up with all the useless channels.

**Comment by janbar** [comment]
Hi,
The addon retrieves only visible channels from your backend. A sample API call done by the addon is:
`http://BACKEND_IP:6544/Channel/GetChannelInfoList?Detail=true&OnlyVisible=true&SourceID=1`
You should check if channel's visibility is really disabled. i.e you could try the API call:
`http://BACKEND_IP:6544/Channel/GetChannelInfoList?OnlyVisible=false&SourceID=1`
and compare the retourned count. Also you could have more than one source. Here I talk about sourceID 1.
The addon create a channel group for each existing source from your backend.

**Comment by 5im-0n** [comment]
Thank you janbar (for this awesome plugin and for the fast response).
You are right: I had the "nice" channels in the "favorites" group on mythtv, I did not set the visible flag.
