### ISSUE TITLE
Addon does not work on odroid C2

### ISSUE THREAD

**Issue by tportenier** [janbar/pvr.mythtv#53]
I am not able to use this addon on odroid C2. I compiled from source, both on arch linux and ubuntu, using kodi-16.1. The kodi log only shows 

`ERROR: ADDON: Dll MythTV PVR Client - Client returned bad status (6) from Create and is not usable`

I can run the same version of the addon (v3.4.19) on x86_64 systems with kodi-16.1 and it also works on my odroid C1+, thus my mythbackend is not the problem. Using libreElec on odroid C2, the addon from the libreElec repository works fine, thus I guess it should be doable. What could be the issue?

**Comment by janbar** [comment]
Hi, only branch "jarvis" can work with kodi 16. Which branch do you have pulled to compile it ? 
The branch to use depends of the kodi version. Which kodi version is installed on your odroid C2 ?

**Comment by tportenier** [comment]
I used this link: https://github.com/janbar/pvr.mythtv/tarball/jarvis

The same tarball also works on C1+ and on x86_64 with kodi 16.1, the same kodi version as on the C2.

**Comment by tportenier** [comment]
The only difference that I see between the working systems and the odroid C2 is the architecture. All systems use the same version of kodi and the same version of pvr.mythtv. Do I need some special configuration option, i.e. compile flag or cmake option in order to make it run on aarch64?

**Comment by janbar** [comment]
The reported message tell us the ABI of the addon is not right with the kodi version. Please pastebin your log file.

**Comment by tportenier** [comment]
I now compiled again using the clone from git, checked out branch jarvis explicitly.  Here is the kodi log:
[kodi.log.txt](https://github.com/janbar/pvr.mythtv/files/650532/kodi.log.txt)

**Comment by janbar** [comment]
log file was generated without debug mode. Any way, I currently compile the addon in my chroot arm64-jessie. I will upload the zip soon.

**Comment by janbar** [comment]
[pvr.mythtv-3.4.19-arm64jessie.zip](https://github.com/janbar/pvr.mythtv/files/652785/pvr.mythtv-3.4.19-arm64jessie.zip)

**Comment by janbar** [comment]
Can you try it ? First you have to uninstall yours else kodi doesn't update the addon with same version.

**Comment by tportenier** [comment]
Thank you for your effort!

I tried your addon (I uninstalled mine before) but the result is the same, the error is also the same. Attached is the kodi.log with debug mode enabled, although there is not much more information in there as far as I can tell.
[kodi.log.txt](https://github.com/janbar/pvr.mythtv/files/653264/kodi.log.txt)

**Comment by janbar** [comment]
mmm, the ABI is not right. Some functions cannot been bound and kodi doesn't try to call function create. I will try to compile a new one against pvr headers from jarvis.

**Comment by janbar** [comment]
A new one compiled against jarvis headers
[pvr.mythtv-3.4.19-arm64.zip](https://github.com/janbar/pvr.mythtv/files/653440/pvr.mythtv-3.4.19-arm64.zip)

**Comment by janbar** [comment]
idem, you have to uninstall first the installed addon, then install this one. hopping that's help.

**Comment by tportenier** [comment]
I tried your new version, it results again in the same error message (log attached).  I previously uninstalled the old addon.
[kodi.log.txt](https://github.com/janbar/pvr.mythtv/files/655412/kodi.log.txt)

**Comment by janbar** [comment]
So I haven't the right toolchain to build for this target. I used a chroot debian/jessie to build for the old project OpenElec. Seems it is no longer possible. You could ask to the maintainer of libreElec what you need to build the addon for its target.

**Comment by tportenier** [comment]
Thank you very much for these clarifications. I wonder why I should not have the right toolchain myself when building natively on the Odroid C2. At least on arm32 (Odroid C1+) this approach worked straightaway. I will try to contact whoever published the libreElec build for the Odroid C2.

**Comment by janbar** [comment]
Also , I am interesting to know the end of this story. Please let me know how you will resolve it.

**Comment by tportenier** [comment]
After debugging this another weekend, I figured out a solution. The key was I realized that it is not a pvr.mythtv problem (other pvr addons don't work either), but a general problem with aarch64. The solution was as follows: On Arch Linux, the following made the plugin work:

sudo ln -s /usr/lib/kodi/addons/library.xbmc.addon/libXBMC_addon-arm64.so /usr/lib/kodi/addons/library.xbmc.addon/libXBMC_addon-i486-linux.so 
sudo ln -s /usr/lib/kodi/addons/library.xbmc.pvr/libXBMC_pvr-arm64.so /usr/lib/kodi/addons/library.xbmc.pvr/libXBMC_pvr-i486-linux.so 
sudo ln -s /usr/lib/kodi/addons/library.kodi.guilib/libKODI_guilib-arm64.so /usr/lib/kodi/addons/library.kodi.guilib/libKODI_guilib-i486-linux.so 
sudo ln -s /usr/lib/kodi/addons/library.xbmc.codec/libXBMC_codec-arm64.so /usr/lib/kodi/addons/library.xbmc.codec/libXBMC_codec-i486-linux.so

On Ubuntu Mate, the following did the trick:

sudo ln -s /usr/lib/aarch64-linux-gnu/kodi/addons/library.xbmc.addon/libXBMC_addon-arm64.so /usr/lib/kodi/addons/library.xbmc.addon/libXBMC_addon-i486-linux.so 
sudo ln -s /usr/lib/aarch64-linux-gnu/kodi/addons/library.xbmc.pvr/libXBMC_pvr-arm64.so /usr/lib/kodi/addons/library.xbmc.pvr/libXBMC_pvr-i486-linux.so 
sudo ln -s /usr/lib/aarch64-linux-gnu/kodi/addons/library.kodi.guilib/libKODI_guilib-arm64.so /usr/lib/kodi/addons/library.kodi.guilib/libKODI_guilib-i486-linux.so 
sudo ln -s /usr/lib/aarch64-linux-gnu/kodi/addons/library.xbmc.codec/libXBMC_codec-arm64.so /usr/lib/kodi/addons/library.xbmc.codec/libXBMC_codec-i486-linux.so

The addon compiles fine and is installable, but fails on enabling. After creating the above symlinks, the addon can be enabled and works as expected.
