### ISSUE TITLE
Setting automatic bookmark on stop fails

### ISSUE THREAD

**Issue by ImNtReal** [janbar/pvr.mythtv#67]
Unfortunately, I'm not sure where this began as I had been ignoring some problems hoping a new release would solve them. Today, I packaged up, and installed 4.13.2. I'm running it against Kodi release 17. I am able to manually create bookmarks, but when it attempts to automatically create one on stop, it fails. Is there other information I can gather or troubleshooting I can perform to help solve this? This is what I see in my log:
`NOTICE: AddOnLog: MythTV PVR Client: SetRecordingLastPlayedPosition: Setting Bookmark failed`

**Comment by ImNtReal** [comment]
I should mention that the backend is MythTV 0.28. Also, Kodi is configured for an external database which is hosted on mariadb 10.1.21.

**Comment by ImNtReal** [comment]
I'll have to wait until I get home to verify, but it looks like it might actually be adding an entry to the database:
```
+------------+--------+---------------+--------------------+---------------------------------------------------------------------+-------------+-------------+------+
| idBookmark | idFile | timeInSeconds | totalTimeInSeconds | thumbNailImage                                                      | player      | playerState | type |
+------------+--------+---------------+--------------------+---------------------------------------------------------------------+-------------+-------------+------+
|        232 |   2083 |           616 |               1798 | special://masterprofile/Thumbnails/Video/Bookmarks/d9688518_616.jpg | VideoPlayer |             |    0 |
|        231 |   2083 |     617.94104 |        1798.791138 |                                                                     | VideoPlayer |             |    1 |
+------------+--------+---------------+--------------------+---------------------------------------------------------------------+-------------+-------------+------+
```

**Comment by janbar** [comment]
If your recording has been transcoded then I think your issue relates same problem than #59.

**Comment by ImNtReal** [comment]
It hasn't. These are MPEG2 files pulled from a HDHR Prime with no
transcoding.

**Comment by janbar** [comment]
Since addon version 4.10 connected to mythtv 0.28, we store the bookmark in mythtv. It wasn t the case since two release because the mythtv api didn t support it.

**Comment by ImNtReal** [comment]
I've updated to 4.14.0, and am still getting the same error. Is there a way I can turn on debugging to get more information about why it failed?

**Comment by ImNtReal** [comment]
Here's an excerpt with --debug:
```
17:26:27.648 T:140494236517696   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
17:26:27.649 T:140492020975360   DEBUG: DoWork - Saving file state for video item pvr://recordings/t
v/active/Default/Chopped/Chopped s32e08 (2017)%20Chefs%20in%20a%20Pickle, TV%20(Food%20Network%20HD)
, 20170222_030000, 1738_1487732400_e29.pvr
17:26:27.656 T:140492020975360   DEBUG: Mysql execute: update files set playCount=NULL,lastPlayed='2
017-02-22 17:26:27' where idFile=2175
17:26:27.662 T:140492020975360   DEBUG: Mysql execute: update bookmark set timeInSeconds = 623.43603
5, totalTimeInSeconds = 3598.290283, thumbNailImage = '', player = 'VideoPlayer', playerState = '' w
here idBookmark = 244
17:26:27.669 T:140492020975360  NOTICE: AddOnLog: MythTV PVR Client: SetRecordingLastPlayedPosition:
 Setting Bookmark failed
17:26:27.669 T:140493848631040   DEBUG: CAnnouncementManager - Announcement: OnUpdate from xbmc
17:26:27.669 T:140493848631040   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnUpdate
17:26:27.729 T:140493748958976   DEBUG: PulseAudio: Stream ready
17:26:27.729 T:140493748958976  NOTICE: PulseAudio: Opened device alsa_output.pci-0000_01_00.1.hdmi-surround-extra1 in pcm mode with Buffersize 150 ms
```

**Comment by ImNtReal** [comment]
I'm not sure what fixed the issue, but I no longer have it. I had upgrade the plugin a few times, and also upgraded my backend to 0.28.1, but I can't pinpoint when it started working.
