### ISSUE TITLE
first letter of recording filename being lowercased

### ISSUE THREAD

**Issue by brianjmurrell** [janbar/pvr.mythtv#68]
Hi,

I hope I can explain this sufficiently.  Please bear with me if it does not come across entirely clear the first time through.

It seems like your plugin, on Kodi 17.x at least, is converting the first letter of a recording's name to lowercase when it sends it to the Myth backend.  So for example, for a _recorded_ table entry of the following:

```
$ echo "select title,subtitle,basename from recorded where title = \"Arrow\" order by starttime;" | mysql -h pvr -u mythtv -p[redacted] mythconverg
title	subtitle	basename
Arrow	Legacy	Arrow: S05E01 - Legacy.mkv
```

When I try to play that recording on Kodi (17 on either Windows 10 or Android) the MythBE emits an error:

```
Feb 24 20:30:22 pvr mythbackend: mythbackend[3152]: E ProcessRequest mainserver.cpp:7944 (LocalFilePath) MainServer: ERROR: LocalFilePath unable to find local path for 'arrow: S05E01 - Legacy.mkv'.
```

So as you can see, the filename being sent to the BE has the first letter lowercased compared to what is in the BE database for the recording.

Admittedly one would normally never notice this for the more typical recordings in a MythBE since their names are typically all numeric digits, but in my case since I am manipulating the filenames post- recording, and updating the database accordingly, I am seeing this defect.

I don't believe I see this on Kodi 16 (on Linux) though.

**Comment by janbar** [comment]
The addon doesn't update the file name. It get it from backend API as the following call:

    http://[backendIp]:6544/Dvr/GetRecordedList?count=100

You could try with a browser searching the recording by title and check what addon handles:

    http://[backendIp]:6544/Dvr/GetRecordedList?TitleRegEx=Arrow

Else IMO some characters couldn't be used in filename as: colon, semi-colon, star and comma. But that's an other point.

**Comment by brianjmurrell** [comment]
This turned out to be a [bug](https://code.mythtv.org/trac/ticket/13006) in MythTV and I have submitted a [PR](https://github.com/MythTV/mythtv/pull/131) to fix it.
