### ISSUE TITLE
Kodi 17 (Odroid C2)

### ISSUE THREAD

**Issue by tportenier** [janbar/pvr.mythtv#71]
I built the addon for Kodi v17 on Odroid C2, using the devel-17 branch. I cannot watch mpeg-2 sd channels in live-tv, playback is stuttering or freezes. It works when playing these files afterwards from the live-tv recordings folder (only after a reboot it seems), but not in live-tv mode. H264 channels work fine also in live-tv. This used to work in Kodi v16.1. If I disable hw acceleration for mpeg-2 it works, but cpu usage is very high and it also stutters sometimes.

**Comment by janbar** [comment]
Thanks to report the issue. The addon doesn't handle directly the payback and hardware acceleration. This issue should be opened for kodi. Please report the bug in kodi tracker.
Maybe this had been reported and it could be resolved with kodi 17.1rc1.
