### ISSUE TITLE
Translation Files

### ISSUE THREAD

**Issue by MikeB2013** [janbar/pvr.mythtv#84]
@janbar 

Just a heads up:

 repo  kodi-pvr/pvr.mythtv has recently had updated translation files committed.
Do you need to pull these into your repo ?

Mike

**Comment by janbar** [comment]
Hi Mike

Yes I need to pull them, because translations haven't yet transferred here. I signaled to the team few months ago but no movement until now.

**Comment by janbar** [comment]
The translations have been merged into master.
