### ISSUE TITLE
Update add-on description to match supported versions

### ISSUE THREAD

**Issue by rockclimb** [janbar/pvr.mythtv#86]
If I've understood the changelog correctly, it seems like MythTV 29 (was 0.29) is supported, but the add-on description in https://github.com/janbar/pvr.mythtv/blob/master/pvr.mythtv/addon.xml.in lists support only up to 0.28, meaning people might think they can't upgrade their backends. It'd be great to get this fixed if possible, although of course it's pretty low priority.
Thanks for the add-on!

**Comment by janbar** [comment]
Yes the addon works with backend 29, as it uses the stable soap API. I will update soon the description for the new kodi release.

**Comment by janbar** [comment]
Done.

**Comment by rockclimb** [comment]
Thanks!
