### ISSUE TITLE
HD live TV channels buffering

### ISSUE THREAD

**Issue by aerans** [janbar/pvr.mythtv#93]
Hello,

I've been using the Mythtv (backend v28) extension on OSMC for some for some time on a Raspberry Pi time and it's worked well. However ....

Over the last 6 or 8 weeks or so I've noticed that live HDTV channels have ceased to work. On the Pi, just a blank screen. SDTV channels worked fine. Video / TV recording replay also work as expected.

I've recently obtained Vero 4k and have the same problem, although in this case, the picture does display but is jerky. Audio seems fine. 

Doing some googling, I increased the buffer size on the Vero but that hasn't cured the problem. 

I've subsequently read that increasing the buffer size doesn't effect the myth extension as it uses a different mechanism. Do you have any idea what the problem may be?

I'm happy to provide logs etc so please let me know if you need anything to help diagnose the problem.

**Comment by janbar** [comment]
Hi, since kodi 17 the addon no longer handles the demuxing of the tv stream. So the only root cause could be in the kodi player itself or hardware support of hd stream (h264). Maybe upgrading kodi could help.

**Comment by aerans** [comment]
Thanks for the feedback. I'll pass this info on to the Vero developers.
