### ISSUE TITLE
Kodi crashes when myth 29.1 is recording

### ISSUE THREAD

**Issue by dbadia** [janbar/pvr.mythtv#98]
When I go to the TV section of Kodi, if the mythtv backend is recording, Kodi crashes.  Log attached.
When mythtv is not recording, I can view the list and watch previously recorded programs without error.

Please let me know what other info I can provide to help test/troublshoot
Dave

[kodi_crashlog-20180328_202117.log](https://github.com/janbar/pvr.mythtv/files/1858229/kodi_crashlog-20180328_202117.log)

**Comment by janbar** [comment]
Thanks for reporting the issue. It is a duplicate of issue #77.
It has to be fixed in kodi. I made a workaround for kodi 17 in the latest version of the addon.

**Comment by janbar** [comment]
Please try to get the latest release of the addon >= 4.15.3.

**Comment by dbadia** [comment]
Apologize for the long delay to retest.  I am still having this issue with 4.15.3.1, running on a ras pi 3+, Koki just reboots continuously. Everything is fine when the backend is not recording.  Crash log is attached when the recording was in progress.  

Let me know if you want me to move this over to #77 and re-open that.

[kodi_crashlog_20181002071502.log](https://github.com/janbar/pvr.mythtv/files/2438106/kodi_crashlog_20181002071502.log)

**Comment by janbar** [comment]
Hi, as the fix hasn't been backported to kodi 17 , you should upgrade to kodi 18 to fix it.

**Comment by dbadia** [comment]
Ah, I understand now.  Working after I upgraded to kodi 18.
